### ISSUE TITLE
MySQL tables not created

### ISSUE THREAD

**Issue by cemmos** [Krytic/MyBBWiki#10]
Hey there. I apologize if there's some type of Github etiquette I don't know of, I've not used the site very often.

I uploaded the plugin and activated it, however, I get the MyBB error:

```
MyBB has experienced an internal SQL error and cannot continue.
SQL Error:
1146 - Table 'mydatabasename.mybb_wiki_perms' doesn't exist
```

Upon checking my database, there are no mybb_wiki_ tables created. Is there something special that I need to do prior to installing the wiki, or is the plugin intended to work as-is?

I would create the tables manually, but sadly I have little knowledge of MySQL/phpMyAdmin and I haven't come across any help documents for the plugin, other than the readme.
- Using the latest version of MyBB (1.8.7)
- mysql  Ver 15.1 Distrib 10.0.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2 on Ubuntu 14.04.5 LTS

Thanks in advance for any assistance, this looks like the best Wiki option for MyBB by far (and the only one that seems to get updates).

**Comment by Krytic** [comment]
Hey Tecca :)

This is indeed a strange issue. MyBB Wiki _should_ work out of the box, so I'm not 100% sure on what would be causing this. I'll run some tests and see what I can find :)

**Comment by cemmos** [comment]
Awesome, thanks for looking into it, Krytic! Once I get this set up and styled, the site should serve as a nice example of how the plugin could look.

**Comment by xensor** [comment]
I got it to work for installing with the new setup. something in the file in the inc/plugins/wiki.php isn't working right. 

i took the old one from mybb extend site and it worked just fine.

these files work but no description field. 

so i took the wiki.php from the plugin folder in inc, and it worked just fine

https://community.mybb.com/mods.php?action=view&pid=653

[wiki.zip](https://github.com/Krytic/MyBBWiki/files/481929/wiki.zip)

copy my wiki file in the zip and upload it. it will work. something in the wiki/inc/plugin/wiki.php isn't working right.

**Comment by Krytic** [comment]
@Tecca @xensor are you both using the latest tagged release, or the content of master? master is bleeding edge and shouldn't be used live, the latest tagged releases are the most stable ones.

I don't recommend downloading the latest from MyBB Extend - I've not updated that in a while and there have been a few schema changes since then. :)

Sorry for the delay testing - finally caught up on my workload, so I should be able to do some thorough testing soon.

**Comment by cemmos** [comment]
That was absolutely it, @Krytic, I was using the contents of master and not the latest release. I actually didn't realize there was a difference between the two — the more you learn ~

Thanks for the help, you two. It seems version 1.1.1 is working absolutely fine. Excited to get this started and add some Wiki content!

**Comment by xensor** [comment]
mine wasn't the master but the tagged and it still gave me errors until i did what i did. 

after i did what i did and activated the plugin i was able to update the files. 

unfort i ended up upgrading to wordpress
