### ISSUE TITLE
Error on plugin page

### ISSUE THREAD

**Issue by Eldenroot** [Krytic/MyBBWiki#12]
Latest GitHub version

Error on plugin page:
![bug](https://cloud.githubusercontent.com/assets/778890/19484809/291c2bb8-9559-11e6-8c2a-89d6904fa2a2.png)

**Comment by Eldenroot** [comment]
@Krytic - please! ;)

**Comment by Krytic** [comment]
Did you download from releases or master? :)

**Comment by Eldenroot** [comment]
master, I wanted to try new features - categoried

**Comment by Krytic** [comment]
I'm not able to test it, but I've just pushed a commit that _should_ fix this issue.

**Comment by Eldenroot** [comment]
@Krytic - thank you, I will test it soon.

Can you please look for this? Any feedback would be welcome
https://github.com/Krytic/MyBBWiki/issues/13

**Comment by Krytic** [comment]
Sorry, am only just getting caught up on older work. I've just finished exams and am in the process of moving. :)
