### ISSUE TITLE
Green/red in text revisions

### ISSUE THREAD

**Issue by Eldenroot** [Krytic/MyBBWiki#14]
Use green/red highlighs for text revisions - red (Deleted), green (Added)

**Comment by Krytic** [comment]
I might be wrong, but that may not be possible with MyBB's inbuilt diff parser. I'll look into it though :)

**Comment by Eldenroot** [comment]
wiki mod from Jones had this feature, maybe you can use the code

**Comment by Eldenroot** [comment]
@Krytic - any way to have this in v1.2.1? Would be really nice

**Comment by Krytic** [comment]
Crawling out of the dust over a year later to comment! It seems that this is already a thing from who knows when. I'm going to tentatively close this, feel free to reopen if I am wrong.
