### ISSUE TITLE
Redirecting back to the article after you protect it do not work

### ISSUE THREAD

**Issue by Eldenroot** [Krytic/MyBBWiki#18]

**Comment by Eldenroot** [comment]
OK, it donest work - no note or change for "Protect article button" in article and the article is not protected. Also redirection is not working.

EDIT: From ACP - it works fine and the note is shown

EDIT2: uid of article is missing in wiki page in navigation

**Comment by Krytic** [comment]
Having a bit of trouble pinning this one down :(

**Comment by Eldenroot** [comment]
@Krytic 

Example:
In article view -> click on "Protect" button - the ID of the article is missing, perhabs php function is not working because there is nothing after "id=". I checked template and there should be a variable loaded but it is not.

http://www.mysite.com/wiki.php?action=protect&id=

However, when you manually add a number of article after id -> protection works fine
http://www.mysite.com/wiki.php?action=protect&id=2

**Comment by SvePu** [comment]
#37
