### ISSUE TITLE
Category description is not saved when you create a new category in ACP

### ISSUE THREAD

**Issue by Eldenroot** [Krytic/MyBBWiki#24]
Category description is not saved when you create a new category in ACP.

You have to go to EDIT and add it again after the category has been created

**Comment by Krytic** [comment]
OK, I've traced where the issue arises, it should be patched by tomorrow :)

**Comment by Eldenroot** [comment]
@Krytic - thank you very much - also this must be fixed (cannot edit articles) - #25

**Comment by Krytic** [comment]
Fixed in the new version :)
