### ISSUE TITLE
PHP error on usergroup delete in ACP

### ISSUE THREAD

**Issue by Eldenroot** [Krytic/MyBBWiki#26]
Fatal error: Uncaught Error: Call to a member function delete_group() on null in /web/inc/plugins/wiki.php:370 Stack trace: #0 
/web/inc/class_plugins.php(139): wiki_admin_user_groups_delete_commit_end('') #1 /web/admin/modules/user/groups.php(1315): pluginSystem->run_hooks(Array) #2 /web/admin/index.php(803): require('/home/users/car...') #3 {main} thrown in /web/inc/plugins/wiki.php on line 370

Latest GitHub version, php 7.0.10

**Comment by Eldenroot** [comment]
@Krytic - any news? I am still waiting for a new bug fix release :( Please

**Comment by Eldenroot** [comment]
@Krytic - only uninstalling plugin can fix this issue - you cannot add/edit any usegroup

**Comment by Krytic** [comment]
This was quite a strange error. I isolated the issue and have fixed it, but I'm not sure why the error was cropping up in the first instance. I suspect it might have something to do with the variable scope in PHP, but idk specifically what. Regardless as I say, here is a commit to fix it :)
