### ISSUE TITLE
NO Wiki admin link

### ISSUE THREAD

**Issue by jefpadfi** [Krytic/MyBBWiki#3]
You mentioned an admin link at the top. It is not there. Linked is a screen shot of my admin panel home page. Would this be done because of the edits we made? Or did it not install correctly?

![nowikilink](https://cloud.githubusercontent.com/assets/7916691/13369323/a6c70b76-dcb0-11e5-91f0-1c6514f23859.png)

**Comment by jefpadfi** [comment]
Loaded up the wiki module while logged into the admin panel. Though there is nothing there to config it with.

![wikimodule](https://cloud.githubusercontent.com/assets/7916691/13369374/3fe96a92-dcb1-11e5-9d4b-b335acfec54b.png)

Again not sure if it is due to the edits that were made to make it work or not.

**Comment by Krytic** [comment]
Please open admin/modules/wiki/module_meta.php, and find `$page->add_menu_item($lang->wiki, "wiki", "index.php?module=wiki", 60, $sub_menu);`. Replace it with `$page->add_menu_item($lang->wiki, "wiki", "index.php?module=wiki", 60, $sub_menu);die('test');` - tell me what you see. Then remove the `die('test');` at the end. :)

**Comment by jefpadfi** [comment]
Looks exactly like the first picture I've posted. Both pages I posted screenshots of, are exactly the same no change.

**Comment by Krytic** [comment]
Are you sure all files are present - not just for the Wiki but also MyBB? It looks like module_meta.php is not being loaded, which is unlikely to be a bug with MyBB Wiki, but I'll look into it regardless.

**Comment by jefpadfi** [comment]
It is suppose to go where Home Configuration etc etc is correct? If so then all files are there for the Arcade mod adds to that top nav no problem.

**Comment by jefpadfi** [comment]
Alo ran the file verification which checks all files for validity. So if a file was corrupted or missing it would list it there. Which When I run it it says it is okay.

**Comment by Krytic** [comment]
File Verification doesn't check plugin files iirc. Can you double check all of MyBB Wiki's files are uploaded?

**Comment by jefpadfi** [comment]
I gotcha now. I'll double check once I'm done with work for the day.

**Comment by Krytic** [comment]
@TheDocter - any news on this?
