### ISSUE TITLE
Cant view wiki pages

### ISSUE THREAD

**Issue by bubba41102** [Krytic/MyBBWiki#6]
For some reason, whenever we create an article, we cannot view any of the text on the article 
[![https://gyazo.com/b2bc513f6c15f29d61187563c9983706](https://i.gyazo.com/b2bc513f6c15f29d61187563c9983706.png)](https://gyazo.com/b2bc513f6c15f29d61187563c9983706)

even though the text exists

[![https://gyazo.com/a1a092c0436134b3872088b7586a2080](https://i.gyazo.com/a1a092c0436134b3872088b7586a2080.png)](https://gyazo.com/a1a092c0436134b3872088b7586a2080)

Any ideas why this might be happening?

**Comment by Krytic** [comment]
Someone else reported this as well. Can you open `inc/plugins/wiki/templates/article.html` and check `{$wiki['content']}` is in that file? Additionally, open the template `wiki_article` in the Admin CP (in the group `Wiki Templates`) and verify the same line is in there. :)
