### ISSUE TITLE
table markdown doesn't work

### ISSUE THREAD

**Issue by xensor** [Krytic/MyBBWiki#9]
it seems like the markdown syntax for tables do not work.

**Comment by Krytic** [comment]
Does other Markdown syntax work?

**Comment by xensor** [comment]
yeah. just table doesn't.

also using the files from here, don't allow me to install. it   gives database error. when i go to plugin page.

**Comment by xensor** [comment]
This is the error:

SQL Error:
    1146 - Table 'uoolo_18212912_5.mybbjh_wiki_perms' doesn't exist
Query:
    DESCRIBE `mybbjh_wiki_perms` 

edit:

I got it to work for installing with the new setup. something in the file in the inc/plugins/wiki.php isn't working right. 

i took the old one from mybb extend site and it worked just fine.

these files work but no description field. 

so i took the wiki.php from the plugin folder in inc, and it worked just fine

https://community.mybb.com/mods.php?action=view&pid=653

[wiki.zip](https://github.com/Krytic/MyBBWiki/files/481929/wiki.zip)

**Comment by xensor** [comment]
I got it to work for installing with the new setup. something in the file in the inc/plugins/wiki.php isn't working right. 

i took the old one from mybb extend site and it worked just fine.


[wiki.zip](https://github.com/Krytic/MyBBWiki/files/481929/wiki.zip)

**Comment by Krytic** [comment]
If it's just the table syntax not working, that might be an issue in the parser, which is 3rd party. :| I'll see what I can do :)

**Comment by Krytic** [comment]
Also, the SQL error is part of #12 :)
